import yaml, os, math

yaml_path = "spec/engines/C008_cognitive_attractor.yaml"
with open(yaml_path, "r") as f:
    spec = yaml.safe_load(f)

p = spec["parameters"]
D = p["D"]
R = p["R"]
PREFILL_STEPS = p["prefill_elaboration_steps"]
DECODE_STEPS = p["decode_steps"]
KAPPA = p["coupling_scale"]
MU = p["mu_attractor"]
TAU_RELAX = p["tau_relax"]
ALPHA = p["eml_scale"]
LAMBDA = p["lyapunov_damping"]

DT = 1.0 / 64.0
HALF_DT = DT / 2.0

print("=================================================================================")
print(f" ⚙️ TRANSPILADOR AOT CANÓNICO :: {spec['engine_id']}")
print(f"    Fuente Única: {yaml_path}")
print("=================================================================================")

# ─── 1. EMITIR SHADER METAL CANÓNICO ─────────────────────────────────────────
metal_code = f"""// ═════════════════════════════════════════════════════════════════════════════
// 🌌 AETHER-VL :: CANONICAL COGNITIVE ATTRACTOR KERNEL (C-008)
// AUTO-GENERATED BY tools/transpilar_c008_engine_aot.py
// ═════════════════════════════════════════════════════════════════════════════
#include <metal_stdlib>
using namespace metal;

constant uint D = {D};
constant uint R = {R};

constant float CANONICAL_KAPPA   = {KAPPA:.12f}f;
constant float CANONICAL_MU      = {MU:.6f}f;
constant float CANONICAL_ALPHA   = {ALPHA:.12f}f;
constant float CANONICAL_LAMBDA  = {LAMBDA:.12e}f;

kernel void c008_project_reductions(
    device const float* Phi                 [[buffer(0)]],
    device const float* Uc                  [[buffer(1)]],
    device const float* Vc                  [[buffer(2)]],
    device const float* Us                  [[buffer(3)]],
    device const float* Vs                  [[buffer(4)]],
    device const float* Ul                  [[buffer(5)]],
    device const float* Vl                  [[buffer(6)]],
    device float* r_proj                    [[buffer(7)]],
    threadgroup float* shared_acc           [[threadgroup(0)]],
    uint r_idx                              [[threadgroup_position_in_grid]],
    uint tid                                [[thread_index_in_threadgroup]],
    uint t_per_group                        [[threads_per_threadgroup]])
{{
    device const float* S = Phi;
    device const float* L = Phi + D;
    uint base_r = r_idx * D;

    float acc_vs_s = 0.0f, acc_us_s = 0.0f;
    float acc_vl_l = 0.0f, acc_ul_l = 0.0f;
    float acc_vc_l = 0.0f, acc_uc_s = 0.0f;
    float local_dot_f_phi = 0.0f;
    float local_norm_sq = 0.0f;

    for (uint i = tid; i < D; i += t_per_group) {{
        float s_val = S[i];
        float l_val = L[i];
        acc_vs_s += Vs[base_r + i] * s_val;
        acc_us_s += Us[base_r + i] * s_val;
        acc_vl_l += Vl[base_r + i] * l_val;
        acc_ul_l += Ul[base_r + i] * l_val;
        acc_vc_l += Vc[base_r + i] * l_val;
        acc_uc_s += Uc[base_r + i] * s_val;

        if (r_idx == 0) {{
            float safe_xs = clamp(-s_val, -20.0f, 20.0f);
            float safe_xl = clamp(-l_val, -20.0f, 20.0f);
            float feml_s = s_val / (1.0f + exp(safe_xs));
            float feml_l = l_val / (1.0f + exp(safe_xl));

            local_dot_f_phi += feml_s * s_val + feml_l * l_val;
            local_norm_sq   += s_val * s_val + l_val * l_val;
        }}
    }}

    #define REDUCE_STORE(var, offset) \\
        shared_acc[tid] = var; \\
        threadgroup_barrier(mem_flags::mem_threadgroup); \\
        for (uint s = t_per_group / 2; s > 0; s >>= 1) {{ \\
            if (tid < s) shared_acc[tid] += shared_acc[tid + s]; \\
            threadgroup_barrier(mem_flags::mem_threadgroup); \\
        }} \\
        if (tid == 0) r_proj[offset * R + r_idx] = shared_acc[0]; \\
        threadgroup_barrier(mem_flags::mem_threadgroup);

    REDUCE_STORE(acc_vs_s, 0);
    REDUCE_STORE(acc_us_s, 1);
    REDUCE_STORE(acc_vl_l, 2);
    REDUCE_STORE(acc_ul_l, 3);
    REDUCE_STORE(acc_vc_l, 4);
    REDUCE_STORE(acc_uc_s, 5);

    if (r_idx == 0) {{
        shared_acc[tid] = local_dot_f_phi;
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint s = t_per_group / 2; s > 0; s >>= 1) {{
            if (tid < s) shared_acc[tid] += shared_acc[tid + s];
            threadgroup_barrier(mem_flags::mem_threadgroup);
        }}
        if (tid == 0) r_proj[6 * R] = shared_acc[0];
        threadgroup_barrier(mem_flags::mem_threadgroup);

        shared_acc[tid] = local_norm_sq;
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint s = t_per_group / 2; s > 0; s >>= 1) {{
            if (tid < s) shared_acc[tid] += shared_acc[tid + s];
            threadgroup_barrier(mem_flags::mem_threadgroup);
        }}
        if (tid == 0) r_proj[6 * R + 1] = shared_acc[0];
    }}
}}

kernel void c008_cognitive_step(
    device const float* Phi_in              [[buffer(0)]],
    device const float* Phi_base            [[buffer(1)]],
    device float* Phi_out                   [[buffer(2)]],
    device const float* Uc                  [[buffer(3)]],
    device const float* Vc                  [[buffer(4)]],
    device const float* Us                  [[buffer(5)]],
    device const float* Vs                  [[buffer(6)]],
    device const float* Ul                  [[buffer(7)]],
    device const float* Vl                  [[buffer(8)]],
    device const float* r_proj              [[buffer(9)]],
    constant float& dt                      [[buffer(10)]],
    constant float& lie_decay               [[buffer(11)]],
    device const float* u_vis               [[buffer(12)]],
    device const float* u_txt               [[buffer(13)]],
    uint tid                                [[thread_position_in_grid]])
{{
    if (tid >= D) return;

    device const float* Vs_S = r_proj + 0 * R;
    device const float* Us_S = r_proj + 1 * R;
    device const float* Vl_L = r_proj + 2 * R;
    device const float* Ul_L = r_proj + 3 * R;
    device const float* Vc_L = r_proj + 4 * R;
    device const float* Uc_S = r_proj + 5 * R;

    float total_dot_f = r_proj[6 * R];
    float total_norm_sq = r_proj[6 * R + 1];
    float proj_factor = (total_norm_sq > 1e-12f) ? (total_dot_f / total_norm_sq) : 0.0f;

    float As_S = 0.0f, Al_L = 0.0f, C_L = 0.0f, neg_CT_S = 0.0f;
    for (uint r = 0; r < R; ++r) {{
        uint idx = r * D + tid;
        As_S     += Us[idx] * Vs_S[r] - Vs[idx] * Us_S[r];
        Al_L     += Ul[idx] * Vl_L[r] - Vl[idx] * Ul_L[r];
        C_L      += Uc[idx] * Vc_L[r];
        neg_CT_S -= Vc[idx] * Uc_S[r];
    }}

    float dot_S = lie_decay * (As_S + CANONICAL_KAPPA * C_L);
    float dot_L = lie_decay * (CANONICAL_KAPPA * neg_CT_S + Al_L);

    float s_in = Phi_in[tid];
    float l_in = Phi_in[tid + D];
    float u_v = u_vis[tid];
    float u_t = u_txt[tid];

    float grad_s = CANONICAL_MU * (u_v - (s_in * u_v) * s_in);
    float grad_l = CANONICAL_MU * (u_t - (l_in * u_t) * l_in);

    float safe_xs = clamp(-s_in, -20.0f, 20.0f);
    float safe_xl = clamp(-l_in, -20.0f, 20.0f);
    float f_eml_s = s_in / (1.0f + exp(safe_xs));
    float f_eml_l = l_in / (1.0f + exp(safe_xl));
    float f_tangent_s = f_eml_s - proj_factor * s_in;
    float f_tangent_l = f_eml_l - proj_factor * l_in;

    float dS = dot_S + grad_s + CANONICAL_ALPHA * f_tangent_s - CANONICAL_LAMBDA * s_in;
    float dL = dot_L + grad_l + CANONICAL_ALPHA * f_tangent_l - CANONICAL_LAMBDA * l_in;

    Phi_out[tid]     = Phi_base[tid]     + dt * dS;
    Phi_out[tid + D] = Phi_base[tid + D] + dt * dL;
}}
"""

with open("metal/aether_c008_cognitive_engine.metal", "w") as f:
    f.write(metal_code)
print("✓ metal/aether_c008_cognitive_engine.metal emitido desde YAML.")

# ─── 2. EMITIR ENCABEZADO C++ MODULAR (include/aether_c008_dispatch.h) ───────
cpp_header = f"""// ═════════════════════════════════════════════════════════════════════════════
// 🌌 AETHER-VL :: C-008 DISPATCH MODULE (AUTO-GENERATED FROM YAML SPEC)
// ═════════════════════════════════════════════════════════════════════════════
#pragma once
#import <Metal/Metal.h>
#include <cmath>
#include <iostream>

struct C008EngineConfig {{
    static constexpr uint32_t D = {D};
    static constexpr uint32_t R = {R};
    static constexpr uint32_t PREFILL_STEPS = {PREFILL_STEPS};
    static constexpr uint32_t DECODE_STEPS  = {DECODE_STEPS};
    static constexpr float DT = {DT:.10f}f;
    static constexpr float HALF_DT = {HALF_DT:.10f}f;
    static constexpr float TAU_RELAX = {TAU_RELAX:.6f}f;
}};

static inline void aether_c008_step_dispatch(
    id<MTLCommandBuffer> cmd,
    id<MTLComputePipelineState> psoRed,
    id<MTLComputePipelineState> psoStep,
    id<MTLBuffer> bufPhi,
    id<MTLBuffer> bufPhiMid,
    id<MTLBuffer> bufRProj,
    id<MTLBuffer> bufUc, id<MTLBuffer> bufVc,
    id<MTLBuffer> bufUs, id<MTLBuffer> bufVs,
    id<MTLBuffer> bufUl, id<MTLBuffer> bufVl,
    float dt_val, float lie_decay_val)
{{
    // Subpaso 1: Reducción
    id<MTLComputeCommandEncoder> enc1 = [cmd computeCommandEncoder];
    [enc1 setComputePipelineState:psoRed];
    [enc1 setBuffer:bufPhi offset:0 atIndex:0];
    [enc1 setBuffer:bufUc offset:0 atIndex:1];
    [enc1 setBuffer:bufVc offset:0 atIndex:2];
    [enc1 setBuffer:bufUs offset:0 atIndex:3];
    [enc1 setBuffer:bufVs offset:0 atIndex:4];
    [enc1 setBuffer:bufUl offset:0 atIndex:5];
    [enc1 setBuffer:bufVl offset:0 atIndex:6];
    [enc1 setBuffer:bufRProj offset:0 atIndex:7];
    [enc1 setThreadgroupMemoryLength:256 * sizeof(float) atIndex:0];
    [enc1 dispatchThreadgroups:MTLSizeMake(C008EngineConfig::R, 1, 1) threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
    [enc1 endEncoding];

    // Subpaso 2: Avance
    id<MTLComputeCommandEncoder> enc2 = [cmd computeCommandEncoder];
    [enc2 setComputePipelineState:psoStep];
    [enc2 setBuffer:bufPhi offset:0 atIndex:0];
    [enc2 setBuffer:bufPhi offset:0 atIndex:1];
    [enc2 setBuffer:bufPhiMid offset:0 atIndex:2];
    [enc2 setBuffer:bufUc offset:0 atIndex:3];
    [enc2 setBuffer:bufVc offset:0 atIndex:4];
    [enc2 setBuffer:bufUs offset:0 atIndex:5];
    [enc2 setBuffer:bufVs offset:0 atIndex:6];
    [enc2 setBuffer:bufUl offset:0 atIndex:7];
    [enc2 setBuffer:bufVl offset:0 atIndex:8];
    [enc2 setBuffer:bufRProj offset:0 atIndex:9];
    float half_dt = dt_val * 0.5f;
    [enc2 setBytes:&half_dt length:sizeof(float) atIndex:10];
    [enc2 setBytes:&lie_decay_val length:sizeof(float) atIndex:11];
    [enc2 setBuffer:bufVs offset:0 atIndex:12]; // u_vis
    [enc2 setBuffer:bufVl offset:0 atIndex:13]; // u_txt
    [enc2 dispatchThreads:MTLSizeMake(C008EngineConfig::D, 1, 1) threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
    [enc2 endEncoding];

    // Subpaso 3: Reducción Mid
    id<MTLComputeCommandEncoder> enc3 = [cmd computeCommandEncoder];
    [enc3 setComputePipelineState:psoRed];
    [enc3 setBuffer:bufPhiMid offset:0 atIndex:0];
    [enc3 setBuffer:bufUc offset:0 atIndex:1];
    [enc3 setBuffer:bufVc offset:0 atIndex:2];
    [enc3 setBuffer:bufUs offset:0 atIndex:3];
    [enc3 setBuffer:bufVs offset:0 atIndex:4];
    [enc3 setBuffer:bufUl offset:0 atIndex:5];
    [enc3 setBuffer:bufVl offset:0 atIndex:6];
    [enc3 setBuffer:bufRProj offset:0 atIndex:7];
    [enc3 setThreadgroupMemoryLength:256 * sizeof(float) atIndex:0];
    [enc3 dispatchThreadgroups:MTLSizeMake(C008EngineConfig::R, 1, 1) threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
    [enc3 endEncoding];

    // Subpaso 4: Avance Final
    id<MTLComputeCommandEncoder> enc4 = [cmd computeCommandEncoder];
    [enc4 setComputePipelineState:psoStep];
    [enc4 setBuffer:bufPhiMid offset:0 atIndex:0];
    [enc4 setBuffer:bufPhi offset:0 atIndex:1];
    [enc4 setBuffer:bufPhi offset:0 atIndex:2];
    [enc4 setBuffer:bufUc offset:0 atIndex:3];
    [enc4 setBuffer:bufVc offset:0 atIndex:4];
    [enc4 setBuffer:bufUs offset:0 atIndex:5];
    [enc4 setBuffer:bufVs offset:0 atIndex:6];
    [enc4 setBuffer:bufUl offset:0 atIndex:7];
    [enc4 setBuffer:bufVl offset:0 atIndex:8];
    [enc4 setBuffer:bufRProj offset:0 atIndex:9];
    [enc4 setBytes:&dt_val length:sizeof(float) atIndex:10];
    [enc4 setBytes:&lie_decay_val length:sizeof(float) atIndex:11];
    [enc4 setBuffer:bufVs offset:0 atIndex:12];
    [enc4 setBuffer:bufVl offset:0 atIndex:13];
    [enc4 dispatchThreads:MTLSizeMake(C008EngineConfig::D, 1, 1) threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
    [enc4 endEncoding];
}}
"""

with open("include/aether_c008_dispatch.h", "w") as f:
    f.write(cpp_header)
print("✓ include/aether_c008_dispatch.h generado modularmente desde YAML.")
